apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  type: NodePort
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31808
  selector:
    app: emqx
